<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net$(GuiSystemDialogsNetVersion)-windows$(GuiSystemDialogsWindowsSdkVersion)</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Gui.SystemDialogs.Wpf.Sharp\Gui.SystemDialogs.Wpf.Sharp.csproj" />
    <ProjectReference Include="..\..\Gui.SystemDialogs.Sharp\Gui.SystemDialogs.Sharp.csproj" />
    <ProjectReference Include="..\Gui.SystemDialogs.TestSupport\Gui.SystemDialogs.TestSupport.csproj" />
  </ItemGroup>
</Project>
